name: RealAI
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "16.0"
targets:
  RealAI:
    type: application
    platform: iOS
    sources:
      - RealAI
    info:
      path: RealAI/Info.plist
      properties:
        CFBundleDisplayName: Real AI
        UILaunchScreen: {}
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.realaiport
        MARKETING_VERSION: "1.6"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
